function (set_xcode_properties TARGET)
  if (APPLE)
    set_target_properties (
      ${TARGET}
      PROPERTIES
        XCODE_ATTRIBUTE_SUPPORTED_PLATFORMS macosx
        XCODE_ATTRIBUTE_SDKROOT macosx
        XCODE_ATTRIBUTE_CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED YES
        XCODE_ATTRIBUTE_CLANG_ANALYZER_NONNULL YES
        XCODE_ATTRIBUTE_CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION YES_AGGRESSIVE
        XCODE_ATTRIBUTE_CLANG_ENABLE_MODULES NO
        XCODE_ATTRIBUTE_CLANG_ENABLE_OBJC_ARC YES
        XCODE_ATTRIBUTE_CLANG_ENABLE_OBJC_WEAK YES
        XCODE_ATTRIBUTE_CLANG_WARN__DUPLICATE_METHOD_MATCH YES
        XCODE_ATTRIBUTE_CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING YES
        XCODE_ATTRIBUTE_CLANG_WARN_BOOL_CONVERSION YES
        XCODE_ATTRIBUTE_CLANG_WARN_COMMA YES
        XCODE_ATTRIBUTE_CLANG_WARN_CONSTANT_CONVERSION YES
        XCODE_ATTRIBUTE_CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS YES
        XCODE_ATTRIBUTE_CLANG_WARN_DIRECT_OBJC_ISA_USAGE YES_ERROR
        XCODE_ATTRIBUTE_CLANG_WARN_DOCUMENTATION_COMMENTS NO
        XCODE_ATTRIBUTE_CLANG_WARN_EMPTY_BODY YES
        XCODE_ATTRIBUTE_CLANG_WARN_ENUM_CONVERSION YES
        XCODE_ATTRIBUTE_CLANG_WARN_FLOAT_CONVERSION YES
        XCODE_ATTRIBUTE_CLANG_WARN_INFINITE_RECURSION YES
        XCODE_ATTRIBUTE_CLANG_WARN_INT_CONVERSION YES
        XCODE_ATTRIBUTE_CLANG_WARN_NON_LITERAL_NULL_CONVERSION YES
        XCODE_ATTRIBUTE_CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF YES
        XCODE_ATTRIBUTE_CLANG_WARN_OBJC_LITERAL_CONVERSION YES
        XCODE_ATTRIBUTE_CLANG_WARN_OBJC_ROOT_CLASS YES_ERROR
        XCODE_ATTRIBUTE_CLANG_WARN_RANGE_LOOP_ANALYSIS YES
        XCODE_ATTRIBUTE_CLANG_WARN_STRICT_PROTOTYPES YES
        XCODE_ATTRIBUTE_CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION YES
        XCODE_ATTRIBUTE_CLANG_WARN_SUSPICIOUS_MOVE YES
        XCODE_ATTRIBUTE_CLANG_WARN_UNGUARDED_AVAILABILITY YES_AGGRESSIVE
        XCODE_ATTRIBUTE_CLANG_WARN_UNREACHABLE_CODE YES
        XCODE_ATTRIBUTE_GCC_DYNAMIC_NO_PIC NO
        XCODE_ATTRIBUTE_GCC_INPUT_FILETYPE automatic
        XCODE_ATTRIBUTE_GCC_NO_COMMON_BLOCKS YES
        XCODE_ATTRIBUTE_GCC_THUMB_SUPPORT NO
        XCODE_ATTRIBUTE_GCC_TREAT_IMPLICIT_FUNCTION_DECLARATIONS_AS_ERRORS YES
        XCODE_ATTRIBUTE_GCC_TREAT_INCOMPATIBLE_POINTER_TYPE_WARNINGS_AS_ERRORS
        YES
        XCODE_ATTRIBUTE_GCC_VERSION com.apple.compilers.llvm.clang.1_0
        XCODE_ATTRIBUTE_GCC_WARN_64_TO_32_BIT_CONVERSION YES_ERROR
        XCODE_ATTRIBUTE_GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS YES
        XCODE_ATTRIBUTE_GCC_WARN_ABOUT_RETURN_TYPE YES_ERROR
        XCODE_ATTRIBUTE_GCC_WARN_HIDDEN_VIRTUAL_FUNCTIONS YES
        XCODE_ATTRIBUTE_GCC_WARN_INITIALIZER_NOT_FULLY_BRACKETED YES
        XCODE_ATTRIBUTE_GCC_WARN_MISSING_PARENTHESES YES
        XCODE_ATTRIBUTE_GCC_WARN_NON_VIRTUAL_DESTRUCTOR YES
        XCODE_ATTRIBUTE_GCC_WARN_SHADOW YES
        XCODE_ATTRIBUTE_GCC_WARN_SIGN_COMPARE YES
        XCODE_ATTRIBUTE_GCC_WARN_UNDECLARED_SELECTOR YES
        XCODE_ATTRIBUTE_GCC_WARN_UNINITIALIZED_AUTOS YES_AGGRESSIVE
        XCODE_ATTRIBUTE_GCC_WARN_UNUSED_FUNCTION YES
        XCODE_ATTRIBUTE_GCC_WARN_UNUSED_VALUE YES
        XCODE_ATTRIBUTE_GCC_WARN_UNUSED_VARIABLE YES
        XCODE_ATTRIBUTE_ALWAYS_SEARCH_USER_PATHS NO
        XCODE_ATTRIBUTE_CODE_SIGN_STYLE Automatic
        XCODE_ATTRIBUTE_ENABLE_BITCODE NO
        XCODE_ATTRIBUTE_ENABLE_STRICT_OBJC_MSGSEND YES
        XCODE_ATTRIBUTE_SKIP_INSTALL YES
        XCODE_ATTRIBUTE_VALIDATE_PRODUCT NO
        COMPILER_INDEX_STORE_ENABLE NO
        XCODE_ATTRIBUTE_COMPILER_INDEX_STORE_ENABLE NO
        XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY libc++
        XCODE_GCC_C_LANGUAGE_STANDARD compiler-default
        XCODE_PRODUCT_NAME $\(TARGET_NAME\)
        XCODE_ATTRIBUTE_DEBUG_INFORMATION_FORMAT
        $<IF:$<CONFIG:Debug>,dwarf,dwarf-with-dsym>
        XCODE_ATTRIBUTE_ENABLE_NS_ASSERTIONS $<IF:$<CONFIG:Debug>,YES,NO>
        XCODE_ATTRIBUTE_ENABLE_TESTABILITY $<IF:$<CONFIG:Debug>,YES,NO>
        XCODE_ATTRIBUTE_GCC_OPTIMIZATION_LEVEL $<IF:$<CONFIG:Debug>,0,3>
        XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH $<IF:$<CONFIG:Debug>,YES,NO>
        XCODE_SCHEME_ENVIRONMENT "OS_ACTIVITY_MODE=disable")
  endif ()
endfunction ()
